### ISSUE TITLE
Will the AWS_S3_HOST setting still work with boto3?

### ISSUE THREAD

**Issue by palewire** [datadesk/django-bakery#100]
Just thought of this. @sheats, you know boto3 better than me. Any thoughts.

**Comment by sheats** [comment]
Ah... the override in settings won't work but it will use boto's value if it's set.

We need to check to see if the value is set [here](https://github.com/datadesk/django-bakery/blob/master/bakery/management/commands/__init__.py#L15) and if so pass it into boto3.client() as [endpoint_url](http://boto3.readthedocs.io/en/latest/reference/core/session.html#boto3.session.Session.client).

**Comment by palewire** [comment]
Thanks. That would great. This setting is probably still important for users who push to buckets with periods in the name.

**Comment by palewire** [comment]
I think we maybe got this.
