### ISSUE TITLE
Output from Logger?

### ISSUE THREAD

**Issue by stvkas** [datadesk/django-bakery#108]
How do you view the output for `logger` instances of the `Logger` class in this application? I'm trying to view the [debugging output from `build_object`](https://github.com/datadesk/django-bakery/blob/master/bakery/views/detail.py#L63), but nothing gets printed to the console when I run `./manage.py build`.

**Comment by stvkas** [comment]
Oh nevermind, I didn't know Django had it's own way of [configuring logging](https://docs.djangoproject.com/en/dev/topics/logging/#configuring-logging).

Here's how I set `LOGGING` in `settings.py` to print `logging` message to the console for the entire project.

```
LOGGING = {
    'version': 1,
    'disable_existing_loggers' : False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'bakery': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'DEBUG'),

        },
    }
}
```

**Comment by palewire** [comment]
Great. Glad to hear it worked out.
