### ISSUE TITLE
Add Django 2.0 compatibility

### ISSUE THREAD

**Issue by rixx** [datadesk/django-bakery#112]
``django-bakery`` has imports from ``django.core.urlresolvers`` which does not exist anymore with Django 2.0, it's ``django.urls`` instead. As this is a blocker for a timely upgrade to Django 2.0, I'd ask you to merge a PR correcting this issue, and releasing a new version soonish.

**Comment by palewire** [comment]
This has shipped as version 0.11

**Comment by rixx** [comment]
Thank you!
