### ISSUE TITLE
deprecated code, as of django 1.10+

### ISSUE THREAD

**Issue by joej** [datadesk/django-bakery#117]
line  120, bakery.py uses:  ... .render(Context(context_variables))
`new_file.write(get_template(template_path).render(Context(context_variables)))`

That is deprecated since 1.10+ and now gives TypeError.
So, simply passing the dictionary fixes this:

`new_file.write(get_template(template_path).render(context_variables))`

**Comment by palewire** [comment]
Thanks for point this out. If the bug has slipped through this far I think we should also consider adding a unit test that run this lineup of code.

**Comment by palewire** [comment]
With more detail about how to recreate this bug, I am closing this ticket.
