### ISSUE TITLE
Allow rendering function views

### ISSUE THREAD

**Issue by NDevox** [datadesk/django-bakery#130]
It's useful to be able to render function views as well as class views, models and templates.

This would allow greater flexibility to do things such as solve issue #88 (the reason why I initially went down this road).

I've used a similar method to solve rendering wagtail sitemaps statically [here](https://gitlab.com/ndevox/nick.sarbicki.com/blob/master/website/views.py#L9).

I'm submitting a PR (as I write this) which does something similar but is a bit more flexible and allows for different types of Django view return types (strings or HttpResponses).

**Comment by palewire** [comment]
This discussion has moved to #131. I think we can close this ticket.
