### ISSUE TITLE
What if you are building your site to be hosted in a subdirectory on a CDN? How do you prefix the URLs during builds?

### ISSUE THREAD

**Issue by palewire** [datadesk/django-bakery#26]
This question came up this morning during [a Twitter conversation](https://twitter.com/adamplayford/status/453894701717155840) with @aplayford. 

Here's an initial idea I have. What if:
- Bakery was expanded to include a set of context processors that would have to be added to the user's ``settings.py.

``` python
TEMPLATE_CONTEXT_PROCESSORS = (
 #... all the usual crap
 'bakery.context_processors.base_url',
 'bakery.context_processors.static_url',
)
```
- Which would create new variables that could be used in each template that looked something like:

``` html+django
<html>
<head>
  <script src="{{ STATIC_URL }}jquery.js"></script>
<body>
  <a href="{{ BASE_URL }}{% url 'homepage' %}">Back to the homepage</a>
</body>
</html>
```
- Then when the template was rendered, the context_processors would analyze the request object they receive and be able to substitute in different values in the baked files by drawing on values in `settings.py` like:

``` python
BUILD_BASE_URL = 'http://www.foobar.com/subdirectory/'
BUILD_STATIC_URL = 'http://www.foobar.com/static/subdirectory/'
```
- I'm not sure how the context processor would know when to make the switch but I suspect it could work something like [this one](http://www.micahcarrick.com/base-url-in-django.html) except it would sniff the request to verify if it came from the [RequestFactory](https://github.com/datadesk/django-bakery/blob/master/bakery/views.py#L35) we use in our buildable views. If that doesn't already include a reliable flag to execute that test, we could expand the views to plant something on the request or in the context dictionary.

Crazy?

**Comment by ghing** [comment]
For what it's worth, this is the approach that I took to use Django Bakery to build the site in a subdirectory.  It uses monkey patching, so be warned.  I put this code inside a Fabric task.  This might be a workable hack for those who need to do this until this issue gets resolved:

```python
    from django.conf import settings
    old_build_dir = settings.BUILD_DIR
    old_static_url = settings.STATIC_URL
    old_initial_reuters_deflection = settings.INITIAL_REUTERS_DEFLECTION;
    settings.INITIAL_REUTERS_DEFLECTION = 'cache'
    settings.BUILD_DIR = os.path.join(settings.BUILD_DIR, settings.ARCHIVE_PATH)
    settings.STATIC_URL = posixpath.join('/', settings.ARCHIVE_PATH,
        settings.STATIC_URL.strip('/')) + '/'

    # HACK: Monkey patch django.core.urlresolvers.reverse to prefix generated URLs with
    # settings.ARCHIVE_PATH
    import django.core.urlresolvers
    old_reverse = django.core.urlresolvers.reverse
    def reverse_patched(viewname, urlconf=None, args=None, kwargs=None, prefix=None, current_app=None):
        url = old_reverse(viewname, urlconf, args, kwargs, prefix, current_app)
        return '/' + settings.ARCHIVE_PATH + url
    setattr(django.core.urlresolvers, 'reverse', reverse_patched)

    # Call Django Bakery's build management command.  Skip copying the static
    # files because the way the management command calculates the target
    # directory based on settings.BUILD_DIR and settings.STATIC_URL doesn't
    # work with the way we've altered these things here.
    management.call_command('build', skip_static=True)

    # Copy static assets to the the build directory.  We do this explicitly
    # here because the ``build`` management command won't calculate the
    # correct directory with our settings.STATIC_URL
    target_dir = os.path.join(old_build_dir, settings.STATIC_URL[1:])

    if getattr(settings, 'BAKERY_GZIP', False):
        # The build management command class has a nice method copytree_and_gzip,
        # but we have to create call it directly if we want to specify the target directory
        cmd = Command()
        cmd.verbosity = 1
        cmd.copytree_and_gzip(settings.STATIC_ROOT, target_dir)
    # if gzip isn't enabled, just copy the tree straight over
    else:
        shutil.copytree(settings.STATIC_ROOT, target_dir)

    # Undo our monkey patches and patched settings
    # This gives the next task a clean slate in case we chain Fabric
    # tasks, e.g. fab chicago archive_build_local archive_publish_local
    settings.BUILD_DIR = old_build_dir
    settings.STATIC_URL = old_static_url
    setattr(django.core.urlresolvers, 'reverse', old_reverse)
```

**Comment by palewire** [comment]
Very interesting. Can you point me to the live example so I can see how it turns out?

**Comment by ghing** [comment]
Let me get back to you on that.  I'm in the process of rolling a new elections.chicagotribune.com which will have the 2014-11-04 election results archived in a "subdirectory" of the S3 bucket.

**Comment by ghing** [comment]
Example of site baked by dynamically adjusting settings and monkey-patching ``django.core.urlresolvers.reverse`` as described in my [previous comment](https://github.com/datadesk/django-bakery/issues/26#issuecomment-68538016): http://elections.chicagotribune.com/2014-11-04/

**Comment by palewire** [comment]
I think I'm going to stop pretending I will ever solve this.

**Comment by palewire** [comment]
There is the new `--aws-bucket-prefix` option on `publish`. I think that's as far as I will ever get unless someone else comes through.

**Comment by aplayford** [comment]
I forgot this thread happened!
