### ISSUE TITLE
Do we want to add Cache-Control headers on our pages?

### ISSUE THREAD

**Issue by emamd** [datadesk/django-bakery#31]
Needs further research, but this could be another big speed and cost improvement. Would need to make sure there are ways to invalidate the cache, and would want a relatively short one for news pages. 

I imagine some static resources - images, css, js, could have farther future headers though.

**Comment by achavez** [comment]
@emand: I ended up implementing this on a per-content type basis in `settings.py`:

```python
BAKERY_CACHE_CONTROL = {
    'text/html': 900
}
```

That'd set `max-age=900` on upload, which we needed because we use CloudFront and didn't want our HTML pages to be subject to their 24-hour default.

I can send a PR if you'd like.

**Comment by palewire** [comment]
Please do.
