### ISSUE TITLE
python setup.py test doesn't discover Django tests for Django >= 1.6

### ISSUE THREAD

**Issue by ghing** [datadesk/django-bakery#63]
You can see this in a [Travis build](https://travis-ci.org/datadesk/django-bakery/jobs/47057013), or by running locally:

```
$ mktmpenv
$ python setup.py test
Creating test database for alias 'default'...
Destroying old test database 'default'...

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
Destroying test database for alias 'default'...
```

This is probably because of the [change in the way tests were discovered with Django 1.6](https://docs.djangoproject.com/en/1.7/releases/1.6/#new-test-runner).

Updating setup.py like this fixes the issue:

```
diff --git a/setup.py b/setup.py
index fcf0155..f4f6f79 100644
--- a/setup.py
+++ b/setup.py
@@ -80,7 +80,7 @@ class TestCommand(Command):
         import django
         if django.VERSION[:2] >= (1, 7):
             django.setup()
-        call_command('test', 'bakery')
+        call_command('test', 'bakery.tests')
```

However, one would probably want to add a guard to only make this change for Django >= 1.6.

**Comment by palewire** [comment]
Ha. And here I thought the tests were passing!

**Comment by ghing** [comment]
@palewire I can fix this.  Would you prefer a separate pull request or should I just add it to the other one?

**Comment by palewire** [comment]
Separate might be better if possible just to keep stuff simple.
