### ISSUE TITLE
DoesNotExist error in unpublish_object task

### ISSUE THREAD

**Issue by achavez** [datadesk/django-bakery#70]
I've been messing with Celery integration and am getting an error that has me wondering about my implementation. It seems that `bakery.views.tasks.unpublish_object()` is being called with `obj_pk` as `None` because the model has already been deleted by the time its info is passed to the task.

I did a workaround, which was to use a pre-delete signal. That allowed for the primary key to be passed correctly, but then, within the task `obj = ct.get_object_for_this_type(pk=obj_pk)` ends up throwing a `DoesNotExist` error because the model is no longer in the database.

I'm guessing I'm missing something here, implementation-wise. Ideas? My short term fix has been to run unbuild while the model still exists, then handle the S3 update asynchronously:

``` python
# my_app/models.py
from my_app import tasks


@receiver(pre_delete, sender=MyModel)
def mymodel_unpublish(sender, instance, **kwargs):
    instance.unbuild()
    tasks.publish_to_s3.delay()
```

``` python
# my_app/tasks.py
from django.conf import settings
from django.core import management

from celery import shared_task


@shared_task()
def publish_to_s3():
    try:
        if not getattr(settings, 'ALLOW_BAKERY_AUTO_PUBLISHING', True):
            logger.info("Not running publish command because \
ALLOW_BAKERY_AUTO_PUBLISHING is False")
        else:
            management.call_command("publish")
    except Exception:
        logger.error("Task Error: unpublish_object", exc_info=True)
```

**Comment by palewire** [comment]
Can you show me an example of where you get the bug?

**Comment by palewire** [comment]
Closing this as stale unless @achavez complains.

**Comment by achavez** [comment]
No complaints here.
