### ISSUE TITLE
CommandError: View %s does not work

### ISSUE THREAD

**Issue by chrisalcantara** [datadesk/django-bakery#74]
When I run the build command, I'm running into `CommandError: View b does not work.` Not sure where b is. The only mention of `b` I know is within a for loop in one of my templates. But even removing the loop doesn't stop this error.

**Comment by palewire** [comment]
Very strange. Can you give me any more details about the code? It could be that something about the content is causing a unicode problem.

**Comment by chrisalcantara** [comment]
I sent you a DM with a link to my code.

**Comment by chrisalcantara** [comment]
Turns out my BAKERY.SETTINGS wasn't configured correctly and threw this error because it couldn't find the view I wrote in `views.py`.

**Comment by palewire** [comment]
Glad it worked out!
