### ISSUE TITLE
TypeError in example using `runserver`

### ISSUE THREAD

**Issue by stvkas** [datadesk/django-bakery#93]
When trying to run the example project, I run into a TypeError from the `get_year` method of the `BuildableDayArchiveView` class. It happens every time I navigate to a MyDayArchiveView using `runsever`. The other views work fine, and I don't get this error with `buildserver`. 

Here's the traceback:
> Environment:
> Request Method: GET
> Request URL: http://127.0.0.1:8090/archive/2015/03/19/
> Django Version: 1.10.5
> Python Version: 2.7.10
> Installed Applications:
> ['django.contrib.admin',
> 'django.contrib.auth',
>  'django.contrib.contenttypes',
>  'django.contrib.sessions',
>  'django.contrib.messages',
>  'django.contrib.staticfiles',
>  'bakery',
>  'date_views']
> 
> Installed Middleware:
> ['django.middleware.security.SecurityMiddleware',
>  'django.contrib.sessions.middleware.SessionMiddleware',
>  'django.middleware.common.CommonMiddleware',
>  'django.middleware.csrf.CsrfViewMiddleware',
>  'django.contrib.auth.middleware.AuthenticationMiddleware',
>  'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
>  'django.contrib.messages.middleware.MessageMiddleware',
>  'django.middleware.clickjacking.XFrameOptionsMiddleware']
> 
> Traceback:
> 
> File "/Users/stephen.kasica/Code/django-bakery/venv/lib/python2.7/site-packages/django/core/handlers/exception.py" in inner
>   39.             response = get_response(request)
> 
> File "/Users/stephen.kasica/Code/django-bakery/venv/lib/python2.7/site-packages/django/core/handlers/base.py" in _legacy_get_response
>   249.             response = self._get_response(request)
> 
> File "/Users/stephen.kasica/Code/django-bakery/venv/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
>   187.                 response = self.process_exception_by_middleware(e, request)
> 
> File "/Users/stephen.kasica/Code/django-bakery/venv/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
>   185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)
> 
> File "/Users/stephen.kasica/Code/django-bakery/venv/lib/python2.7/site-packages/django/views/generic/base.py" in view
>   68.             return self.dispatch(request, *args, **kwargs)
> 
> File "/Users/stephen.kasica/Code/django-bakery/venv/lib/python2.7/site-packages/django/views/generic/base.py" in dispatch
>   88.         return handler(request, *args, **kwargs)
> 
> File "/Users/stephen.kasica/Code/django-bakery/venv/lib/python2.7/site-packages/django/views/generic/dates.py" in get
>   339.         self.date_list, self.object_list, extra_context = self.get_dated_items()
> 
> File "/Users/stephen.kasica/Code/django-bakery/venv/lib/python2.7/site-packages/django/views/generic/dates.py" in get_dated_items
>   586.         year = self.get_year()
> 
> File "/Users/stephen.kasica/Code/django-bakery/venv/lib/python2.7/site-packages/django_bakery-0.8.12-py2.7.egg/bakery/views/dates.py" in get_year
>   239.         dt = date(int(self.year), int(self.month), int(self.day))
> 
> Exception Type: TypeError at /archive/2015/03/19/
> Exception Value: int() argument must be a string or a number, not 'NoneType'

I'm wondering if I didn't set up the project correctly. Here's how I set up my project after `git clone`:
```
$ pip install -r requirements.txt
$ python setup.py install
$ ./manage.py migrate
$ ./manage.py loaddata date_views/fixtures/initial_data.json
```

**Comment by palewire** [comment]
A quick read of the code suggests to me that [this line](https://github.com/datadesk/django-bakery/blob/master/bakery/views/dates.py#L238) of bakery is crashing when it tries to convert the year attribute of your view into an integer. Rather than a number or a string that can be converted, the view says the value is a ``NoneType`` null object, which is causing the crash.

The URL ``/archive/2015/03/19/`` appears to be the type of thing we'd want, but I wonder if it is being properly parsed by the URL pattern and handed off to the view. Would you mind posting the URL pattern you've linked with the view?

**Comment by stvkas** [comment]
My `example/project/url.py` is as it comes "[out of the box](https://github.com/datadesk/django-bakery/blob/master/example/project/urls.py)".

But I've read more of the code now, and I learned that [this implementation](https://github.com/datadesk/django-bakery/blob/master/bakery/views/dates.py#L233) of the `get_year` method doesn't do the same searching for the year value that the [original implementation](https://github.com/django/django/blob/master/django/views/generic/dates.py#L34) does. I could be wrong, but I think the unformatted year value is in `self.kwargs['year']`, but the method expects it to be in `self.year`.

`BuildableYearArchiveView` and `BuildableMonthArchiveView` overrides `get_year` and `get_month` by post-filtering. Why not do the same in `BuildableDayArchiveView`?

**Comment by palewire** [comment]
Hmm. That could be an oversight in how I wrote the code. I see what you mean, the month view has something like this before it parses the year as an integer.

```python
year = super(BuildableMonthArchiveView, self).get_year()
```
 
I guess we should try something similar here?

**Comment by palewire** [comment]
I just tested you bug and I think recreated on my end. I have pushed a patch and new release PyPI at version 0.8.13. Try upgrading with:

```python
pip install django-bakery --upgrade
```

**Comment by stvkas** [comment]
Yep, that patch is working for me, too. Thanks for the quick response! I'm really hoping I can use this app in a project at work.

**Comment by palewire** [comment]
Great. Thanks for the bug report.

If you publish something, let me know. I'm always interested to hear how people are using this tool.
