### ISSUE TITLE
commands are writing to sys.stdout, rather than self.stdout

### ISSUE THREAD

**Issue by ginabythebay** [datadesk/django-bakery#96]
I would like to call the 'build' command via [management.call_command](https://docs.djangoproject.com/en/1.10/ref/django-admin/).  Unfortunately I see in the source code that output is sent using six.print_ without specifying self.stdout, so it instead goes to sys.stdout.  This makes it very difficult for my code to capture the results of the call.

The django documentation [recommends](https://docs.djangoproject.com/en/1.10/howto/custom-management-commands/) writing to self.stdout.  If it sounds like a good change to you, I would be happy to submit a PR that changes all command calls to six.print_ to include file=self.stdout

**Comment by palewire** [comment]
Sounds good. We should be doing whatever "default" Django management commands are doing as a model for best practices. I'd love the patch.
