### ISSUE TITLE
Define custom SERVER_NAME in RequestFactory

### ISSUE THREAD

**Issue by robmoorman** [datadesk/django-bakery#98]
When having a multisite setup, we get trouble with receiving the hostname from the request. In our case a 'Site' object in Wagtail determines the existing url based on hostname routing. With 'testserver' (Django's default SERVER_NAME for RequestFactory) this gives us always our default site.

I would like to suggest to create an extra method for retrieving the RequestFactory (e.g. `get_request_factory`).

Seems like a good idea? I can create a PR on agreement on this. Please let me know.

FYI; we're extending this module (thanks!) to build all pages in our Wagtail CMS to static files (https://github.com/moorinteractive/wagtail-bakery).

**Comment by palewire** [comment]
Yes. That sounds like a fine idea. I'm a big fan of making classes extendable in this manner.

Also, if you have some ideas about "sensible defaults" to pass into the standard RequestFactory, I'm open to changes there as well.

**Comment by robmoorman** [comment]
Great, I'll do some work on that upcoming week! Thanks.

**Comment by robmoorman** [comment]
Oh nvm it's already there on the master `def create_request` in the mixin.
Would be nice to have the latest versions shipped out on short notice btw :) (boto3 and this).

**Comment by palewire** [comment]
Great.

I believe that create_request is in the latest released version. Boto is still limited to the master branch and I'm hoping to do some more testing of that one released projects before I ship it. If you get a chance to try it out too that would be a help.

Thanks.

**Comment by palewire** [comment]
Also, I wonder if there might be a way to send the request factory through all the context processors in the settings file. Would that be "djangoish" and solve this problem and others like it at the same time?

**Comment by robmoorman** [comment]
Ok cool, will do some runs with it tomorrow (boto3)!

I think a separate setting for context processor wouldn't be necessary, as context processors are used in templates. As their is no reasons why a RequestFactory should be read from a template...
